## ANN on Churning data of Bank

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
data.describe()

In [5]:
X = data.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = data['Exited']

In [6]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])

In [10]:
label = LabelEncoder()
X['Gender'] = label.fit_transform(X['Gender'])
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [11]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

In [12]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
X_test

array([[ 8.33260665e-01, -1.08620280e+00, -9.50812388e-02, ...,
         1.23198813e+00, -5.84086250e-01, -5.71384156e-01],
       [-5.53096261e-02, -1.08620280e+00,  1.89309306e-01, ...,
         5.12724231e-01,  1.71207591e+00, -5.71384156e-01],
       [-3.34279369e-01,  9.20638397e-01,  1.61126203e+00, ...,
         7.29241616e-01, -5.84086250e-01, -5.71384156e-01],
       ...,
       [ 8.74589516e-01, -1.08620280e+00, -9.50812388e-02, ...,
        -1.42477054e-01, -5.84086250e-01, -5.71384156e-01],
       [ 3.88975520e-01, -1.08620280e+00, -2.84390545e-04, ...,
        -8.19941321e-01, -5.84086250e-01, -5.71384156e-01],
       [ 7.29938538e-01,  9.20638397e-01,  6.63293547e-01, ...,
         4.39338151e-02, -5.84086250e-01, -5.71384156e-01]])

### Applying ANN

In [16]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [17]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [18]:
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 100, verbose = 1)

Epoch 1/100
800/800 [==============================] - 4s 4ms/step - loss: 0.4712 - accuracy: 0.7956
Epoch 2/100
800/800 [==============================] - 3s 3ms/step - loss: 0.4074 - accuracy: 0.8291
Epoch 3/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3720 - accuracy: 0.8484
Epoch 4/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3514 - accuracy: 0.8569
Epoch 5/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3422 - accuracy: 0.8584
Epoch 6/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3390 - accuracy: 0.8599
Epoch 7/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3354 - accuracy: 0.8608
Epoch 8/100
800/800 [==============================] - 3s 4ms/step - loss: 0.3339 - accuracy: 0.8626
Epoch 9/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3328 - accuracy: 0.8619
Epoch 10/100
800/800 [==============================] - 3s 3ms/step - loss: 0.3302 - accura

In [19]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")


63/63 [==============================] - 1s 4ms/step


In [20]:
y_pred

array([[0],
       [1],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [21]:
y_test

7878    1
3224    1
1919    1
4432    0
4835    0
       ..
9073    1
8584    0
5390    1
5092    1
2964    0
Name: Exited, Length: 2000, dtype: int64

In [22]:
model.evaluate(X_test, y_test.to_numpy())

63/63 [==============================] - 1s 4ms/step - loss: 0.3887 - accuracy: 0.8445


[0.3887493312358856, 0.8445000052452087]

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
confusion_matrix(y_test, y_pred)

array([[1520,   97],
       [ 214,  169]], dtype=int64)

In [28]:
accuracy_score(y_test,y_pred)*100

84.45